export * from './ArrOfObjectsToSingleObject';
export * from './ArrToObject';
export * from './SessionPersistence/SessionDelete';
export * from './SessionPersistence/SessionPersistence';
export * from './VerifyIsDomain';
export * from './VerifyIsEmail';
export * from './knowWhenPageReload';
export * from './toBeSingular';
export * from './toCapitalizeFirstLetter';
